Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: create.lambda_handler
      CodeUri: C:\repo\orders-api\orders-api
      Runtime: python3.9
      Architectures:
        - x86_64