AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: python3.9
    Timeout: 30
    Architectures:
      - x86_64
    Environment:
      Variables:
        ORDERS_TABLE: !Ref OrdersTable

Resources:
  OrdersTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: Number

  CreateOrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: orders-api/
      Handler: create.lambda_handler
      Events:
        CreateOrders:
          Type: Api
          Properties:
              Path: /orders
              Method: POST
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref OrdersTable
  ReadOrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: orders-api/
      Handler: read.lambda_handler
      Events:
        ReadOrders:
          Type: Api
          Properties:
              Path: /orders/{id}
              Method: GET
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref OrdersTable
Outputs:
  CreateOrdersAPI:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/orders/"
  CreateOrderFunction:
    Value: !GetAtt CreateOrderFunction.Arn
  CreateOrderFunctionRole:
    Value: !GetAtt CreateOrderFunctionRole.Arn